### ISSUE TITLE
0.2.2 PTXprint TypeError

### ISSUE THREAD

**Issue by LouKehler** [sillsdev/ptx2pdf#12]
I haven't been able to get PTXprint to print anything yet. It fails with the following error:

Traceback (most recent call last):
  File "ptxprint\__init__.py", line 203, in onOK
  File "ptxprint", line 96, in doit
  File "ptxprint\info.py", line 183, in __init__
  File "ptxprint\info.py", line 195, in update
  File "ptxprint\info.py", line 360, in makelocalChanges
  File "ptxprint\info.py", line 433, in ListMissingPics
  File "ntpath.py", line 135, in join
  File "genericpath.py", line 149, in _check_arg_types
TypeError: join() argument must be str or bytes, not 'ParatextSettings'

[PTXprint 0.2.2 TypeError failure log.txt](https://github.com/sillsdev/ptx2pdf/files/3875760/PTXprint.0.2.2.TypeError.failure.log.txt)

**Comment by mhosken** [comment]
The short answer is: don't do that! You tried to print a project that had no project id. I agree it shouldn't crash though :)

**Comment by markpenny** [comment]
OK, we now trap an empty projid and emit this message:
![image](https://user-images.githubusercontent.com/12962708/69399780-6947aa00-0d15-11ea-9113-205133164d27.png)

There will be an updated .exe (likely v0.2.3) later in the day containing this fix. If you're still getting an error, then re-open this issue and tell us more. Thanks.
