### ISSUE TITLE
0.2.3 PTXprint project and book schizophrenia

### ISSUE THREAD

**Issue by LouKehler** [sillsdev/ptx2pdf#16]
I got my first project through PTXprint with version 0.2.3 by unselecting the Include illustrations checkbox. Yeah! However, I am still seeing some confusion when changing the project. This seems to be the problem I was having with 0.2.2. The first time I ran it I forgot to select a project before hitting OK. Then, even though it allowed me to select a project from the pulldown menu, I could see from the log file that it was not properly setting the project throughout, but instead, was still somehow trying to print the blank project.
Now, with 0.2.3 right after I started it up I selected the project PBSU and the book of RUT when I hit the OK button it generated an error:

	No pages of output.
	Transcript written on ptxprint-RUTPBSU.log.
	cd C:/My Paratext 8 Projects\PBSU\PrintDraft; xetex ptxprint-RUTPBSU.tex -> 1
	Traceback (most recent call last):
	  File "ptxprint", line 137, in removeTempFiles
	FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/My Paratext 8 Projects\\PBSU\\PrintDraft\\ptxprint-RUTPBSU.delayed'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "ptxprint\__init__.py", line 214, in onOK
	  File "ptxprint", line 123, in doit
	  File "ptxprint", line 139, in removeTempFiles
	NameError: name 'Gtk' is not defined
	
Then without restarting the program I changed the project to HUFT and ran it again and got the following error:

	No pages of output.
	Transcript written on ptxprint-RUTPBSU.log.
	cd C:/My Paratext 8 Projects\PBSU\PrintDraft; xetex ptxprint-RUTPBSU.tex -> 1
	Traceback (most recent call last):
	  File "ptxprint", line 137, in removeTempFiles
	FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/My Paratext 8 Projects\\PBSU\\PrintDraft\\ptxprint-RUTPBSU.delayed'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "ptxprint\__init__.py", line 214, in onOK
	  File "ptxprint", line 123, in doit
	  File "ptxprint", line 139, in removeTempFiles
	NameError: name 'Gtk' is not defined
	Picture Path: C:/My Paratext 8 Projects\PBSU\Figures
	Traceback (most recent call last):
	  File "ptxprint\__init__.py", line 214, in onOK
	  File "ptxprint", line 104, in doit
	  File "ptxprint\info.py", line 193, in update
	  File "ptxprint\info.py", line 387, in makelocalChanges
	  File "ptxprint\info.py", line 477, in ListMissingPics
	FileNotFoundError: [Errno 2] No such file or directory: 'C:/My Paratext 8 Projects\\PBSU\\01GENHUFT.SFM'

Note that even though the Paratext Project is now set to HUFT, from the log it is apparent that it is confused. The final error illustrates the problem. It is looking in the old project folder PBSU for the file with the new project name 01GENHUFT.SFM. Also, the book selected has gone back to GEN when I switched projects but it somehow also still thinks it is RUT. The first part of the error message is trying to work with RUT and gets an exception within an exception where the second exception thinks it is printing GEN.
Switching the Single Book dropdown menu to RUT and running doesn't help. It still has both project and book schizophrenia as illustrated in the log:

	No pages of output.
	Transcript written on ptxprint-RUTPBSU.log.
	cd C:/My Paratext 8 Projects\PBSU\PrintDraft; xetex ptxprint-RUTPBSU.tex -> 1
	Traceback (most recent call last):
	  File "ptxprint", line 137, in removeTempFiles
	FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/My Paratext 8 Projects\\PBSU\\PrintDraft\\ptxprint-RUTPBSU.delayed'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "ptxprint\__init__.py", line 214, in onOK
	  File "ptxprint", line 123, in doit
	  File "ptxprint", line 139, in removeTempFiles
	NameError: name 'Gtk' is not defined
	Picture Path: C:/My Paratext 8 Projects\PBSU\Figures
	Traceback (most recent call last):
	  File "ptxprint\__init__.py", line 214, in onOK
	  File "ptxprint", line 104, in doit
	  File "ptxprint\info.py", line 193, in update
	  File "ptxprint\info.py", line 387, in makelocalChanges
	  File "ptxprint\info.py", line 477, in ListMissingPics
	FileNotFoundError: [Errno 2] No such file or directory: 'C:/My Paratext 8 Projects\\PBSU\\01GENHUFT.SFM'
	Picture Path: C:/My Paratext 8 Projects\PBSU\Figures
	Traceback (most recent call last):
	  File "ptxprint\__init__.py", line 214, in onOK
	  File "ptxprint", line 104, in doit
	  File "ptxprint\info.py", line 193, in update
	  File "ptxprint\info.py", line 387, in makelocalChanges
	  File "ptxprint\info.py", line 477, in ListMissingPics
FileNotFoundError: [Errno 2] No such file or directory: 'C:/My Paratext 8 Projects\\PBSU\\08RUTHUFT.SFM'

Seeing that these errors are related to missing pics, I unselected "Include illustrations" and walla it generated output for the book of Ruth in the HUFT project. So now I try to go back to the original project I wanted to print, PBSU, and make sure the book of RUT is selected and "include illustrations" is not. This time I still fail with:

	No pages of output.
	Transcript written on ptxprint-RUTPBSU.log.
	cd C:/My Paratext 8 Projects\PBSU\PrintDraft; xetex ptxprint-RUTPBSU.tex -> 1
	Traceback (most recent call last):
	  File "ptxprint", line 137, in removeTempFiles
	FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/My Paratext 8 Projects\\PBSU\\PrintDraft\\ptxprint-RUTPBSU.delayed'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "ptxprint\__init__.py", line 214, in onOK
	  File "ptxprint", line 123, in doit
	  File "ptxprint", line 139, in removeTempFiles
	NameError: name 'Gtk' is not defined

This time no schizophrenia but no joy either. Restarting PTXprint still produces the same error. I suppose I could create a file "ptxprint-RUTPBSU.delayed" for it to remove but this doesn't seem quite right.

**Comment by mhosken** [comment]
I think this arose because of a bug in changing projects to a project for which there is no existing ptxprint.cfg configuration. Hopefully this is fixed. But it may not :)

**Comment by LouKehler** [comment]
That helped. If the print fails for any reason, it now shows a warning that it can't delete each missing temporary file but keeps going. That allowed me to discover what was making XeTeX fail. It turned out that I had some previously customized Scripture Macro files in the PrintDraft folder for that project and they were interfering. After deleting the PrintDraft folder and running PTXprint again, it recreated the PrintDraft folder and ran correctly.
