### ISSUE TITLE
Diglots failing in usfmerge 

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#230]
related to #202, or something else?

New diglot project, both sub-projects produce monoglots fine, engage diglot option, Press Print:
```
Traceback (most recent call last):
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 361, in digdojob
    usfmerge(left, right, outFile, stylesheetsa=sheetsa, stylesheetsb=sheetsb)
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/usfmerge.py", line 290, in usfmerge
    canonicalise_footnotes=True, tag_escapes=tag_escapes))
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/sfm/__init__.py", line 674, in _default_
    e.extend(sub_parser(e))
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/sfm/__init__.py", line 674, in _default_
    e.extend(sub_parser(e))
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/sfm/__init__.py", line 674, in _default_
    e.extend(sub_parser(e))
  [Previous line repeated 1 more time]
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/sfm/usfm.py", line 371, in g
    if prev.meta['StyleType'] == 'Character':
AttributeError: 'Text' object has no attribute 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/gtkview.py", line 532, in onOK
    self.callback(self)
  File "/home/david/src/ptx2pdf/python/scripts/ptxprint", line 121, in doit
    runjob.doit()
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 194, in doit
    self.texfiles += sum((self.digdojob(j, info, diginfo, digprjid, digprjdir) for j in joblist), [])
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 194, in <genexpr>
    self.texfiles += sum((self.digdojob(j, info, diginfo, digprjid, digprjdir) for j in joblist), [])
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 365, in digdojob
    print(self.prjid, b, str(e).split('line', maxsplit=1)[1])
IndexError: list index out of range
```

**Comment by mhosken** [comment]
It's probably using some unknown sfm marker. Shame we can't find out which.
That's more the bug!

GB,
Martin

**Comment by davidg-sil** [comment]
Would this be the case even if the Advanced / Auto-correct USFM is ticked for both projects? It is.

**Comment by mhosken** [comment]
The difference is that auto correct does not canonicalise footnotes and usfmerge does. The error is in the badly formed footnote. At least that's what the usfm parser considers it to be. Without access to the text we can't decide whether it is right or wrong in that assumption. I'm open to turning off canonicalising footnotes in usfmerge.

**Comment by davidg-sil** [comment]
OK... it looks like I've got some genuinely messy footnotes:
 e.g. \f ...\fq text \fq* \ft text \fq text \fq*  text \f*

I'll fix that and try again.
If there hadn't been the  console log, all I would have observed was click
button, nothing happens.

I think that since the cannoncalising in usfmerge  is crashing like that in
footnotes, and not reporting back to (GUI) users, it's probably not worth
having.
Diglot switching mid-footnote shouldn't be allowed to happen anyway, so I
don't see why it's usmerge's business to dig that deep, really. It should
be ignoring char styles. and just insisting that Note styles don't get
broken by par styles.
You get balrogs if you dig too deep....

**Comment by mhosken** [comment]
Removed canonicalising footnotes during usfmerge.
