### ISSUE TITLE
Still problems with Saving Configuration

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#376]
Steps I took:

- start working in a new project
- shift to advanced mode, select several books
- enter a new name in the Configuration Name, click Save
- new name is not in the Configuration list

If I change interface language, the Configuration Name seems to show up. But then I deleted that configuration, and tried to go to another project and got:

Please send this error message to ptxprint_support@sil.org

PTXprint Version 1.5.9.3

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1739, in onProjectChange
  File "ptxprint\gtkview.py", line 1767, in updateProjectSettings
  File "ptxprint\view.py", line 325, in updateProjectSettings
  File "ptxprint\gtkview.py", line 721, in writeConfig
  File "ptxprint\piclist.py", line 520, in writeCfg
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\My Paratext 8 Projects\\Djcdist\\shared\\ptxprint\\Epistles\\picChecks.txt'

**Comment by jeffheath-sil** [comment]
Still some weird things here... I follow the exact steps listed above, the newly named configuration doesn't show up in list, and if I change UI language, I get:

Please send this error message to ptxprint_support@sil.org

PTXprint Version 1.5.14

Traceback (most recent call last):
  File "configparser.py", line 788, in get
  File "C:\msys64\mingw64\lib\python3.7\collections\__init__.py", line 916, in __getitem__
  File "C:\msys64\mingw64\lib\python3.7\collections\__init__.py", line 908, in __missing__
KeyError: 'topmarginfactor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1791, in onProjectChange
  File "ptxprint\gtkview.py", line 1819, in updateProjectSettings
  File "ptxprint\view.py", line 389, in updateProjectSettings
  File "ptxprint\view.py", line 469, in readConfig
  File "ptxprint\view.py", line 621, in versionFwdConfig
  File "configparser.py", line 823, in getfloat
  File "configparser.py", line 808, in _get_conv
  File "configparser.py", line 802, in _get
  File "configparser.py", line 791, in get
configparser.NoOptionError: No option 'topmarginfactor' in section: 'paper'

So I would say not fixed... :-)
