### ISSUE TITLE
v1.5.10  fails to build an archive file

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#389]
When I try to create an archive file for you all, whether I check the keep temp files or not, it starts the process and then fails with: 

Please send this error message to ptxprint_support@sil.org

PTXprint Version 1.5.10

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1970, in onCreateZipArchiveClicked
  File "ptxprint\view.py", line 1067, in createArchive
  File "ptxprint\view.py", line 1082, in _archiveAdd
  File "ptxprint\view.py", line 954, in _getArchiveFiles
  File "ptxprint\piclist.py", line 857, in getFigureSources
KeyError: 'src'

<class 'KeyError'>: 'src'

**Comment by mhosken** [comment]
Something to do with a picture not have a src. Do you have any empty pictures in there? I've put something in to not crash in that case.

**Comment by davidc86** [comment]
I have no empty pictures that I know of. Here is my current archive: 
https://1drv.ms/u/s!AsIa18BQPThpr78k2UdDxdArC-0Eww?e=uFO0Ne
I had to insert my Front Matter pdf in there because it wasn't included (see #393), but this is what I get now. So the process is working again.
