### ISSUE TITLE
Errors with Bible module

### ISSUE THREAD

**Issue by be601** [sillsdev/ptx2pdf#416]
Hi
I tried out a Bible Module, and came across these two errors:

1. This one after choosing the Bible Module and pressing Print
![image](https://user-images.githubusercontent.com/79921788/109820964-8d977380-7c46-11eb-91ac-bf1355a296c4.png)

2. Then I changed the font to one I know is installed for all users, pressed Print, and this error (it also seemed to not close Paratext, as I got a message that PT was already running when I tried to run it afterwards):
==== 
Please send this error message to ptxprint_support@sil.org

PTXprint Version 1.5.15

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 723, in onOK
  File "ptxprint", line 163, in doit
  File "ptxprint\runjob.py", line 190, in doit
  File "ptxprint\runjob.py", line 190, in <genexpr>
  File "ptxprint\runjob.py", line 309, in dojob
  File "ptxprint\texmodel.py", line 693, in convertBook
  File "ptxprint\texmodel.py", line 644, in flattenModule
  File "ptxprint\usfmutils.py", line 440, in __init__
  File "ptxprint\usfmutils.py", line 377, in read_module
  File "C:\msys64\mingw64\lib\python3.7\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

<class 'UnicodeDecodeError'>: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
====

**Comment by mhosken** [comment]
I did add some resilience so it doesn't crash.
