### ISSUE TITLE
Create archive fails

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#484]
Traceback (most recent call last):
  File "python\scripts\..\lib\ptxprint\gtkview.py", line 2365, in onCreateZipArchiveClicked
    self.createArchive(str(archiveZipFile[0]))
  File "python\scripts\..\lib\ptxprint\view.py", line 1316, in createArchive
    trailer = PdfReader(pf)
  File "python\scripts\..\lib\ptxprint\pdfrw\pdfreader.py", line 585, in __init__
    raise PdfParseError('Empty PDF file!')
ptxprint.pdfrw.errors.PdfParseError: Empty PDF file!

<class 'ptxprint.pdfrw.errors.PdfParseError'>: Empty PDF file!

**Comment by markpenny** [comment]
Also, after creating an archive (successfully or not), I have to close PTXprint because I'm blocked by this message:
![image](https://user-images.githubusercontent.com/12962708/130738265-6d9c0a2d-86fc-4143-9bef-a560ae3a860a.png)
