### ISSUE TITLE
Bible module error

### ISSUE THREAD

**Issue by be601** [sillsdev/ptx2pdf#593]
PTXprint Version 2.0.15
Please send to: ptxprint_support@sil.org

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 930, in onOK
  File "ptxprint", line 198, in doit
  File "ptxprint\runjob.py", line 254, in doit
  File "ptxprint\runjob.py", line 254, in <genexpr>
  File "ptxprint\runjob.py", line 378, in dojob
  File "ptxprint\texmodel.py", line 1008, in convertBook
  File "ptxprint\texmodel.py", line 954, in flattenModule
  File "ptxprint\usfmutils.py", line 584, in parse
  File "ptxprint\usfmutils.py", line 641, in parse_element
  File "ptxprint\usfmutils.py", line 616, in parse_element
  File "ptxprint\usfmutils.py", line 646, in get_passage
AttributeError: 'NoneType' object has no attribute 'upper'

<class 'AttributeError'>: 'NoneType' object has no attribute 'upper
[TXY-TXYPerikopaPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/7624473/TXY-TXYPerikopaPTXprintArchive.zip)
'

**Comment by markpenny** [comment]
This is related to markup in the module. See my e-mail response.

**Comment by mhosken** [comment]
we should probably still not crash if we can avoid it. Problem duly masked :)
