### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#6]
I have tried using this program on most of the projects I have access to, but have not been able to get it to run yet. Most often I'm seeing errors like this:
```
Traceback (most recent call last):
  File "ptxprint\__init__.py", line 203, in onOK
  File "ptxprint", line 109, in doit
  File "ptxprint", line 56, in dojob
  File "C:\msys64\mingw64\lib\python3.7\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2688-2689: character maps to <undefined>
```

I've tried a few different fonts and sometimes the position numbers change (and sometimes I get the error regarding featvals), but there are no other changes.

**Comment by mnjames** [comment]
I was able to get things to successfully run using 0.2.2.
