### ISSUE TITLE
Refresh Fonts Error

### ISSUE THREAD

**Issue by rdai** [sillsdev/ptx2pdf#621]
PTXprint Version 2.1.1
Please send to: ptxprint_support@sil.org

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 2025, in onRefreshFontsclicked
  File "ptxprint\font.py", line 244, in fccache
  File "ptxprint\font.py", line 150, in runFcCache
  File "ptxprint\runner.py", line 39, in checkoutput
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['C:/Program Files/PTXprint/xetex/bin/fc-cache.exe']' returned non-zero exit status 3221226356.

**Comment by markpenny** [comment]
Hi @rdai! I have been able to replicate this and have discovered that it is related to user-level permissions. I'm not yet sure how we will solve it, but the easiest work-around is to run PTXprint as Administrator, and then the error disappears.
![image](https://user-images.githubusercontent.com/12962708/154651768-52dec51b-7083-49b9-bbeb-b837e6d91b08.png)

**Comment by rdai** [comment]
Thanks Mark, good enough for me.
