### ISSUE TITLE
New choose chapter ranges and "Hide Empty Verses" are incompatible.

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#632]
If I choose to print a group of multiple books with chapter ranges, e.g. `1CO 2CO 1-6 GAL`,  it works fine.
If I choose to "Hide empty verses", it works fine.
However, if I try to do both at the same time I get the error
```
PTXprint Version 2.1.8
Please send to: ptxprint_support@sil.org



Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1017, in onOK
  File "ptxprint", line 204, in doit
  File "ptxprint\runjob.py", line 270, in doit
  File "ptxprint\runjob.py", line 270, in <genexpr>
  File "ptxprint\runjob.py", line 395, in dojob
  File "ptxprint\texmodel.py", line 1141, in convertBook
  File "ptxprint\usfmutils.py", line 565, in stripEmptyChVs
  File "ptxprint\usfmutils.py", line 511, in iterfn
  File "ptxprint\usfmutils.py", line 556, in iterfn
ValueError: list.remove(x): x not in list

<class 'ValueError'>: list.remove(x): x not in list
```

**Comment by mnjames** [comment]
Actually, I think this probably pre-dated the recent addition of chapter ranges in multiple books. Even in single books, if a subset of chapters is chosen it conflicts with "Hide empty verses".
