### ISSUE TITLE
python3.10 issue in Jammy package

### ISSUE THREAD

**Issue by n7s** [sillsdev/ptx2pdf#675]
a traceback from running PTXprint from the .deb package as built by Launchpad for jammy: 

Traceback (most recent call last):
  File "/usr/bin/ptxprint", line 114, in <module>
    from ptxprint.gtkview import GtkViewModel, getPTDir, reset_gtk_direction
  File "/usr/lib/python3/dist-packages/ptxprint/gtkview.py", line 24, in <module>
    from ptxprint.view import ViewModel, Path, VersionStr, GitVersionStr
  File "/usr/lib/python3/dist-packages/ptxprint/view.py", line 3, in <module>
    from ptxprint.texmodel import ModelMap, TexModel, Borders
  File "/usr/lib/python3/dist-packages/ptxprint/texmodel.py", line 9, in <module>
    from ptxprint import sfm
  File "/usr/lib/python3/dist-packages/ptxprint/sfm/__init__.py", line 278, in <module>
    class _put_back_iter(collections.Iterator):
AttributeError: module 'collections' has no attribute 'Iterator'

Might it be because of python3.10 changes?

**Comment by n7s** [comment]
Jammy has Python 3.10.4

**Comment by markpenny** [comment]
Thanks for the heads-up @n7s ! I'm guessing this is an issue for @mhosken to dig into; but it is unlikely to happen this week due to the LT Dev Conf. Presumably this is the 1st time that a package has been built for Jammy.

**Comment by n7s** [comment]
yes, I understand it's early days for the Jammy version (and the dependencies there) the recipe has been turned on just a few days ago, what I find I will flag under the packaging tag. No urgency from me :-)
