### ISSUE TITLE
Orphan Marker \f error

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#765]
I'm getting the following error, and can't figure out why. I've run marker checks inside of PT and don't see any obvious problems. It's extremely possible it's caused by badly formed data, but it's happening in more than one project which makes me wonder if it is or isn't.

```Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1250, in onOK
  File "ptxprint", line 223, in doit
  File "ptxprint\runjob.py", line 292, in doit
  File "ptxprint\runjob.py", line 292, in <genexpr>
  File "ptxprint\runjob.py", line 452, in dojob
  File "ptxprint\texmodel.py", line 1859, in createXrefTriggers
  File "ptxprint\usfmutils.py", line 96, in get
  File "ptxprint\usfmutils.py", line 148, in __init__
  File "ptxprint\sfm\__init__.py", line 732, in _default_
    self._error(ErrorLevel.Unrecoverable,
  File "ptxprint\sfm\__init__.py", line 599, in _error
    raise SyntaxError(msg)
SyntaxError: D:\Documents\UP\My Paratext 8 Projects\XXX\41MATXXX.SFM: line 39,369 [id]: orphan marker \f

<class 'SyntaxError'>: D:\Documents\UP\My Paratext 8 Projects\XXX\41MATXXX.SFM: line 39,369 [id]: orphan marker \f


PTXprint Version 2.2.35
```

**Comment by mnjames** [comment]
Thanks. So far so good.
