### ISSUE TITLE
Failed to delete/reset 'Default' configuration

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#800]
Traceback (most recent call last):
  File "c:/ptx2pdf/python/lib/ptxprint/gtkview.py", line 1410, in onDeleteConfig
    self.updateProjectSettings(self.prjid)
  File "c:/ptx2pdf/python/lib/ptxprint/gtkview.py", line 2958, in updateProjectSettings
    if not super(GtkViewModel, self).updateProjectSettings(prjid, saveCurrConfig=saveCurrConfig, configName=configName, readConfig=readConfig):
  File "c:/ptx2pdf/python/lib/ptxprint/view.py", line 576, in updateProjectSettings
    self.working_dir = os.path.join(self.settings_dir, self.prjid, "local", "ptxprint", configName)
  File "C:/msys64/mingw64/lib/python3.9/ntpath.py", line 137, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:/msys64/mingw64/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

PTXprint Version 2.2.43-g1b03a85e

**Comment by markpenny** [comment]
Deleting other configs works fine; but not the "Default" config -- which should be resetting all the settings, and removing the stylesheet customizations etc.
