### ISSUE TITLE
pathlib related issue in Ubuntu Noble (soon to be released as 24.04)

### ISSUE THREAD

**Issue by n7s** [sillsdev/ptx2pdf#946]
```
test@testing:~$ ptxprint 
Traceback (most recent call last):
  File "/usr/bin/ptxprint", line 20, in <module>
    from ptxprint.utils import saferelpath
  File "/usr/lib/python3/dist-packages/ptxprint/utils.py", line 594, in <module>
    class Path(pathlib.Path):
  File "/usr/lib/python3/dist-packages/ptxprint/utils.py", line 596, in Path
    _flavour = pathlib._windows_flavour if os.name == "nt" else pathlib._posix_flavour
                                                                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pathlib' has no attribute '_posix_flavour'
```

**Comment by mhosken** [comment]
Thanks. Now I know you can do conditional inheritance!
