### ISSUE TITLE
hyphen.py errors > 2.5.3

### ISSUE THREAD

**Issue by 1-John** [sillsdev/ptx2pdf#970]
Since updating to the 2.5.5 started giving error (prev version 2.5.3)
when hyphenation is used I following errors:

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1565, in onOK
  File "ptxprint.py", line 248, in doit
  File "ptxprint\runjob.py", line 410, in doit
  File "ptxprint\runjob.py", line 410, in <genexpr>
  File "ptxprint\runjob.py", line 616, in dojob
  File "ptxprint\texmodel.py", line 995, in convertBook
  File "ptxprint\usfmutils.py", line 277, in hyphenate
  File "ptxprint\usfmutils.py", line 274, in proc
  File "ptxprint\usfmutils.py", line 274, in proc
  File "ptxprint\usfmutils.py", line 274, in proc
  File "ptxprint\usfmutils.py", line 276, in proc
  File "ptxprint\hyphen.py", line 165, in hyphenate
NameError: name 'accumulate' is not defined

<class 'NameError'>: name 'accumulate' is not defined

PTXprint Version 2.5.5

-----------------

Mailto: <ptxprint_support@<your.org's.address>>

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1564, in onOK
  File "ptxprint.py", line 248, in doit
  File "ptxprint\runjob.py", line 410, in doit
  File "ptxprint\runjob.py", line 410, in <genexpr>
  File "ptxprint\runjob.py", line 616, in dojob
  File "ptxprint\texmodel.py", line 995, in convertBook
  File "ptxprint\usfmutils.py", line 277, in hyphenate
  File "ptxprint\usfmutils.py", line 274, in proc
  File "ptxprint\usfmutils.py", line 274, in proc
  File "ptxprint\usfmutils.py", line 274, in proc
  File "ptxprint\usfmutils.py", line 276, in proc
  File "ptxprint\hyphen.py", line 161, in hyphenate
NameError: name 'hyph' is not defined

<class 'NameError'>: name 'hyph' is not defined

PTXprint Version 2.5.4

---------------

downgrading to 2.5.2 solves the issues (the 2.5.3 is not on the website anymore)

**Comment by markpenny** [comment]
Apologies for this regression. This has been fixed in 2.5.6 which will be released shortly. (2.5.3 was removed from the website as we discovered an issue with it).
