### ISSUE TITLE
The (c) ... button dialog acted weird

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#985]
I tried to set up the (c) David C. Cook text for one of the DCC pictures in the project using the (c) ... button. In that dialog window, I specified the text and location of the notification, and then I selected the option to propagate this to all pictures in the series. 

I got this error message:

--------
Mailto: <ptxprint_support@sil.org>

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 5133, in onOverlayCreditClicked
AttributeError: 'Piclist' object has no attribute 'values'

PTXprint Version 2.6.5
-------

I closed the error message.
Then 
* I tried to click OK at the copyright dialog, nothing happened.
* I tried to click Cancel at the copyright dialog, nothing happened.
* I clicked on the X button, and it finally closed the dialog.

When I exported the PDF. PTXprint did place the (c) David C. Cook text on the picture I was working on, but it did NOT propagate this request to all the other DCC pictures in the project.

 After exporting the PDF, I returned to PTXprint to add another (c) David C. Cook text to another picture (mostly to see if things were still working or not). It's now worse. The dialog won't open and I get this error message: 
-------
Mailto: <ptxprint_support@sil.org>

Traceback (most recent call last):
  File "ptxprint\gtkutils.py", line 66, in setWidgetVal
  File "ptxprint\gtkutils.py", line 55, in _setcomboval
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 5120, in onOverlayCreditClicked
  File "ptxprint\gtkview.py", line 1412, in set
  File "ptxprint\gtkutils.py", line 103, in setWidgetVal
TypeError: Setting <Gtk.ComboBoxText object at 0x0000015ad6fbd980 (GtkComboBoxText at 0x0000015a91dd8230)>, 'NoneType' object is not iterable

PTXprint Version 2.6.5
--------

I closed and reopening PTXprint and tried the (c) dialog again. 
If I just do ONE picture at a time, all functions okay.
But when I try to "Apply to ALL images in this series" I get the same error message as the first one.

**Comment by markpenny** [comment]
@davidc86 Thanks for reporting this. We have recently reworked the whole back end of the Pictures code, and there are no doubt more bugs to be ironed out. Keep looking for them :-)

**Comment by mhosken** [comment]
You do realise that we don't need to have in image credits for DCC images any more (unconfirmed)

**Comment by markpenny** [comment]
This works for me in 2.6.8 - please check if this has been fixed now. If not, come back to us.

**Comment by davidc86** [comment]
It kind of works. 
I don't get the error message above when I click "propagate to all", but PTXprint doesn't remember the settings from one session to the next. (#986).

@mhosken said "You do realise that we don't need to have in image credits for DCC images anymore (unconfirmed)" 
Yes, I've heard this is true, but to keep publications consistent with previously published versions, it would be nice to still have this feature. (And there could be cases where other artists would like their pictures so marked. So, it would be great to have it working again.)
